import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#050505",
  },
  header: {
    height: 115,
    paddingHorizontal: 22,
    paddingTop: 35,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#050505",
    zIndex: 1,
  },
  logo: {
    color: "#E60023",
    fontSize: 36,
    fontWeight: "900",
  },
  logoBlanco: {
    color: "#FFFFFF",
    fontSize: 24,
    fontWeight: "800",
  },
  headerIcons: {
    flexDirection: "row",
    gap: 18,
  },
  body: {
    flex: 1,
    flexDirection: "row",
    paddingHorizontal: 8,
    paddingBottom: 10,
  },
  sidebar: {
    width: "38%",
    backgroundColor: "#0D0D0D",
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 4,
    marginRight: 4,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    marginTop: 10,
    paddingHorizontal: 6,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
    marginLeft: 4,
    letterSpacing: 1,
  },
  marginTop: {
    marginTop: 25,
  },
  contactItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderRadius: 14,
    marginBottom: 6,
  },
  contactActive: {
    backgroundColor: "rgba(230,0,35,0.22)",
  },
  avatarContainer: {
    position: "relative",
    marginRight: 10,
    marginTop: 2,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 25,
    backgroundColor: "#222",
  },
  initialAvatarContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#333333",
    alignItems: "center",
    justifyContent: "center",
  },
  initialAvatarText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
  },
  initialAvatarHeader: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  initialAvatarHeaderText: {
    fontSize: 20,
  },
  initialAvatarMessage: {
    width: 26,
    height: 26,
    borderRadius: 13,
    marginRight: 8,
    marginBottom: 2,
  },
  initialAvatarMessageText: {
    fontSize: 12,
  },
  statusDot: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 12,
    height: 12,
    borderRadius: 10,
    backgroundColor: "#30D158",
    borderWidth: 2,
    borderColor: "#0D0D0D",
  },
  statusAway: {
    backgroundColor: "#8A8A8A",
  },
  contactName: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  contactStatus: {
    color: "#8A8A8A",
    fontSize: 12,
    marginTop: 2,
  },
  badge: {
    backgroundColor: "#E60023",
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "auto",
  },
  badgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "900",
  },
  chatPanel: {
    flex: 1,
    backgroundColor: "#0D0D0D",
    borderRadius: 18,
    overflow: "hidden",
  },
  chatHeader: {
    height: 80,
    borderBottomWidth: 1,
    borderBottomColor: "#1F1F1F",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  chatAvatar: {
    width: 44,
    height: 44,
    borderRadius: 25,
  },
  chatHeaderInfo: {
    flex: 1,
    marginLeft: 12,
  },
  chatName: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
  },
  chatStatus: {
    color: "#B8B8B8",
    fontSize: 13,
    marginTop: 2,
  },
  messages: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 15,
    backgroundColor: "#0F0F0F",
  },
  dayBox: {
    alignSelf: "center",
    backgroundColor: "#222",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginBottom: 15,
  },
  dayText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 12,
  },
  messageRow: {
    flexDirection: "row",
    marginBottom: 14,
    alignItems: "flex-end",
  },
  messageLeft: {
    justifyContent: "flex-start",
  },
  messageRight: {
    justifyContent: "flex-end",
  },
  messageAvatar: {
    width: 26,
    height: 26,
    borderRadius: 15,
    marginRight: 8,
    marginBottom: 2,
  },
  bubble: {
  maxWidth: "75%",
  minWidth: 180, // ← agrega esta línea
  borderRadius: 16,
  paddingHorizontal: 14,
  paddingVertical: 10,
  },
  otherBubble: {
    backgroundColor: "#242424",
    borderBottomLeftRadius: 4,
  },
  myBubble: {
    backgroundColor: "#C9142B",
    borderBottomRightRadius: 4,
  },
  messageText: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 22,
  },
  messageTime: {
    color: "#CFCFCF",
    fontSize: 10,
    marginTop: 4,
    alignSelf: "flex-end",
  },
  inputArea: {
    height: 70,
    borderTopWidth: 1,
    borderTopColor: "#1F1F1F",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 10,
    backgroundColor: "#0D0D0D",
  },
  circleButton: {
    width: 36,
    height: 36,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#E60023",
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    flex: 1,
    backgroundColor: "#151515",
    borderRadius: 20,
    color: "#FFFFFF",
    paddingHorizontal: 15,
    height: 40,
    fontSize: 14,
  },
  bottomNav: {
    flexDirection: "row",
    backgroundColor: "#050505",
    borderTopWidth: 1,
    borderTopColor: "#1F1F1F",
    paddingTop: 15,
    paddingBottom: 60, // Espacio extra masivo para Android
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
  },
  navText: {
    color: "#8A8A8A",
    fontSize: 10,
    marginTop: 4,
  },
  navTextActive: {
    color: "#FF4D67",
    fontWeight: "bold",
  },
  smallBadge: {
    position: "absolute",
    right: -6,
    top: -6,
    backgroundColor: "#E60023",
    width: 14,
    height: 14,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  smallBadgeText: {
    color: "white",
    fontSize: 8,
    fontWeight: "bold",
  },
});

export default styles;
